version: '1.25'
services:
  server:
    image: gbarnacle79/server
    build: ./server
    deploy:
      replicas: 2
  name:
    image:  gbarnacle79/name_gen
    build: ./name
  prize:
    image: gbarnacle79/prize_gen
    build: ./prize
    deploy:
      replicas: 2
  fortune:
    image:  gbarnacle79/fortune_gen
    build: ./fortune
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
